### ISSUE TITLE
Extend std_sync_reg

### ISSUE THREAD

**Issue by paili0628** [cucapra/futil#1025]
**Discussed in #932**
@paili0628 will be working on these two PRs advised by @rachitnigam:

- [ ] Extend std_sync_reg to 2 writers:

- Add ports
- Build (smart) arbiter to select which writer's input to write into the register
- Implement tests in calyx

- [ ] Extend std_sync_reg to 2 readers:

- Add ports
- Build (smart) arbiter to select which reader to give its output to
- Implement tests in calyx

**Comment by rachitnigam** [comment]
Sweet, this looks great! One thought that occurred to me is using a one-hot encoding to build a smart arbiter: whenever the vector of writes is one-hot, no need to arbitrate. Otherwise, pick one.
