### ISSUE TITLE
Add `ap_idle` signal

### ISSUE THREAD

**Issue by nathanielnrn** [cucapra/futil#1078]
Part of #1072

**Comment by nathanielnrn** [comment]
Need to understand flags found [here](https://github.com/cucapra/calyx/blob/924d879764c669fc464b75f8286e1a989e252c2e/src/backend/xilinx/control_axi.rs#L32-L47)

**Comment by sampsyo** [comment]
This is probably too obvious to be helpful, but it looks like those flags do have some human-readable comments here:
https://github.com/cucapra/calyx/blob/924d879764c669fc464b75f8286e1a989e252c2e/src/backend/xilinx/axi_address_space.rs#L9-L19
