### ISSUE TITLE
Trivial Par Removal

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#112]
This pass should detect instances where
```
(par (enable A B) (enable C D))
```
is equivalent to:
```
(enable A B C D)
```
and make the corresponding conversion. This pass may be remarkably similar to the automatic parallelization pass.

**Comment by rachitnigam** [comment]
Doesn't [redundant-par](https://github.com/cucapra/futil/blob/master/calyx/src/passes/redundant_par.rs) already do this?

**Comment by sgpthomas** [comment]
Redundant-par is incorrect right now since it will merge all `par`s regardless of whether it's safe. So redundant-par should be replaced with this. We could potentially keep the name though

**Comment by rachitnigam** [comment]
I'm going to mark this as high-pri because redundant-par doing the wrong thing is confusing and might lead us down the wrong way when building passes that run after it.

**Comment by rachitnigam** [comment]
Futil has been redesigned to use go/done holes and groups in #139.
