### ISSUE TITLE
Latency insensitive pass captures port names

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#119]
If there ports named `ready` or `valid` already present in the component, the pass will add new ports with the same names causing a conflict.

The pass should either rename the existing ports when a conflict occurs or generate new names for the `ready` and `valid` ports.

Minimal example:
```racket
(define/namespace prog
 (define/component comp1 ((port valid 1)) ((port ready 1))
  ()
  (seq)))
```

which generates:
```
(define/component comp1
  ((port valid 1) (port valid 1))
  ((port ready 1) (port ready 1))
  ()
  (seq))
```

**Comment by sgpthomas** [comment]
I've fixed this in `mvp_verilog`

**Comment by sgpthomas** [comment]
https://github.com/cucapra/futil/pull/94/files#diff-f602af88b28120b3485ab34caeb434e9R19

**Comment by rachitnigam** [comment]
I don't think that's the right fix. You've given special semantics to named port. What happens if that port is being used for something else?

The proposed solutions above treat the existing wires as if they already have an internal semantics for the program and try to preserve it.

**Comment by sgpthomas** [comment]
Yeah you’re right. It would be better to just error out for now then. We need to think more about how to add semantically meaningful ports / wires
