### ISSUE TITLE
Futil backend printing is non-determinisitic

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#122]
*sigh*

**Comment by sgpthomas** [comment]
yep, turns out HashMaps are random. You should probably fix this by fixing the random seed that the hashmap is using :p

**Comment by rachitnigam** [comment]
Fixed by https://github.com/cucapra/futil/commit/e2a51066e6fd04e8e84f2e450ec0a56b813a7d6e

**Comment by rachitnigam** [comment]
That seems like the wrong solution. I just sort the keys before printing them.
