### ISSUE TITLE
Cannot `invoke` a `ref` cell

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#1649]
@paili0628 also ran into when building the HiSparse design in Calyx. At a high-level, the problem is that we do `compile-ref` before `compile-invoke`. Let's look at an example:
```
comp main() {
  cells { F = Foo(), B = Bar () }
  invoke F[bar = B](...)
}

comp Foo() {
  cells { ref B = Bar() }
  invoke B()
}
```

First, `compile-refs` runs:
```
comp main() {
  cells { F = Foo(), B = Bar () }
  invoke F[bar = B](...)
}

comp Foo(/* Bar's ports */) {
  cells { /* Bar is removed as a cell */ }
  invoke B() // <- unknown cell
}
```

The right solution is to merge `compile-invoke` and `compile-ref` into one pass so that during the compilation of invokes, we can wire up the `ref` cell correctly within a group and allow it to be invoked.

**Comment by rachitnigam** [comment]
The current blocker is that we run a bunch of optimization passes run between `compile-ref` and `compile-invoke` because those passes don't yet support `ref` cells:
```
                CompileRef
                ComponentInliner,
                CombProp,
                CellShare, // LiveRangeAnalaysis should handle comb groups
                SimplifyWithControl, // Must run before infer-static-timing
                CompileInvoke, // creates dead comb groups
```

To actually support this, we must first change the passes to support `ref` cells.

**Comment by rachitnigam** [comment]
In those examples do we ever invoke a component that is itself a `ref` cells? If so, I'm surprised that worked?

**Comment by anshumanmohan** [comment]
Ah you're right. In the examples above, the invoked component is a vanilla (non-`ref`) cell. It's just that the invoked component _takes inputs by reference_, meaning that it has in _its_ `cells` block some `ref` cell(s). I see now that my examples above are sorta besides the point when it comes to this issue.

The subtly different point of #1648 is that, _even_ when all the invoked components are vanilla (non-`ref`) cells, if they have `ref` inputs within them, and you make a chain of these invokes, you run into trouble.

**Comment by sampsyo** [comment]
This is a super subtle (and seemingly important) pass interaction. I like @rachitnigam's summary that:

> At a high-level, the problem is that we do `compile-ref` before `compile-invoke`.

This is a fundamental problem because it only makes sense to `invoke` things that are actual cells, and `compile-ref` destroys the "integrity" of cells, smashing them up into a bunch of interface wires instead.

I am certain this will not work, but I don't have a clear description about why: could we "just" move `compile-invoke` before `compile-ref`? This would first turn the invokes into manipulations of the component's ports (`compile-invoke`); it would then rewire those ports to ports on the parent component (`compile-ref`). I'm sure I'm missing something here, but it must be a different problem from the current one.

Maybe this would be an interesting topic for the synchronous Calyx meeting sometime?

**Comment by rachitnigam** [comment]
I was originally thinking of doing something similar (moving `compile-ref` after `compile-invoke`) but the problem is that there is no direct way to represent passing `ref` cells structurally:
```
invoke foo[a=r](...)
```
Here, the assignment `a=r` is the cell `r` being passed for the ref cell argument `a` but there is no way to turn this into a group representation in `compile-invoke`; we have to represent it using the assignments implied by the ref cell assignment.

Put differently, `compile-ref` changes the signature of a module so that it can be structurally invoked (invoked using a group) which means `compile-invoke`, which transforms control invocations into structural ones cannot run before it.

**Comment by sampsyo** [comment]
Ah, thanks for helping me along. I'm starting to get the sense that this could be a good synchronous discussion, but I wonder if we could still somehow make this work—i.e., to allow structural use of `ref` cells, and thus allow `compile-invoke` to go first.

Borrowing your example, we want this to work:

```
comp Foo() {
  cells { ref B = Bar() }
  control { invoke B() }
}
```

In a fantasy world, if `compile-invoke` went first, this would turn into a structural use of the `ref` cell named `B`. Something like this:

```
comp Foo() {
  cells { ref B = Bar() }
  wires {
    group invoke1 {
      B.go = 1;
      invoke1[done] = B.done;
    }
  }
  control { invoke1 }
```

And then later, when `compile-ref` runs, it replaces those `B.go` and `B.done` port references with `B_go` and `B_done` ports on `Foo`. (Or hooks them up with `std_wire`s or whatever.) Is this an unreasonable thing to imagine?

**Comment by rachitnigam** [comment]
Yeah, that case makes sense to me (invoking a `ref` cell). I'm talking about the case where you pass `ref` cells by argument:
```
comp Foo() {
  cells { ref B = Bar() }
}
comp Baz {
  cells { B0 = Bar(), F = Foo() }
  control {
    invoke F[B=B0](...)
  }
}
```
When compiling this program, if you run `compile-invoke` before `compile-ref`, what is the compiler supposed to do when it sees the `[B=B0]` argument? There is no way to turn that into a group.

**Comment by sampsyo** [comment]
Ah, right, of course—I don't know why I keep losing track of which case this problem exists in (invoking cells? invoking ref-cells? invoking cells with cell arguments? invoking cells with ref-cell arguments? invoking ref-cells with non-ref-cell arguments? it's all a bit much 😂).

That's pretty convincing. You would have to work very hard to allow structural "passing" of "cell arguments" in the absence of `invoke`… something like:

```
group invoke1 {
  F.B = B0;
  invoke1[done] = F.done;
}
```

which is very very weird; what are we even doing with that `F.B = B0` assignment. So yeah, I think we're back to square 1 (thanks for leading me back there), i.e., `compile-invoke` and `compile-ref` unfortunately need to get glued together.
