### ISSUE TITLE
Infer static timing

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#177]
Proposal to implement a pass that can infer/validate static timing for some simple cases.

We can infer the timing of a group if two things are true:
1. The groups's done signal relies only on other done signals.
2. The assignment to every go signal in the group is only guarded using only `done` signals.

For example, in the trivial group:
```
group do_something {
  r1.in = go ?  1'd1;
  do_something[done] = r1.done;
}
```
we can deduce the group requires 1 cycle since the delay between `r1.in` and `r1.done` is 1 cycle.

More complicated cases work by induction:
1. Chain of done signals (2 cycles)
```
group do_something {
  r1.in = go ?  1'd1;
  r2.in = r1.done ? 1'd1;
  do_something[done] = r2.done;
}
```
2. Guards with `and` and `or` (1 cycle)
```
group do_something {
  r1.in = go ?  1'd1;
  r2.in = r1.done ? 1'd1;
  r3.in = go ? 1'd1;
  do_something[done] = r2.done || r3.done;
}
```

We can use this pass for two things: (1) Infer the timing of groups and (2) validate timing annotations. (2) only needs to conservatively calculate the minimum time and error when the annotation has `"static"` less than that value.

Todo:
- [ ] Run this pass on the systolic array code
- [ ] Rethink whether or not this needs recursion

**Comment by sampsyo** [comment]
This is a very nifty idea. I like the thought that this could also be used for catching bugs when the frontend messes up the annotations.
