### ISSUE TITLE
Relay: Link with Dahlia-compiled kernels

### ISSUE THREAD

**Issue by sampsyo** [cucapra/futil#186]
Per [this Slack thread](https://cucapra.slack.com/archives/CLLM75W4R/p1596838413166100?thread_ts=1596834757.161000&cid=CLLM75W4R), a good route to compiling larger-scale Relay programs will be to invoke kernels pre-written in Dahlia. For the tensor-add example from #184, for example, we could write a `for`-based add kernel in Dahlia and compile it to FuTIL. Then the Relay-to-FuTIL compiler would instantiate this component to implement the `add` instruction from Relay.

**Comment by cgyurgyik** [comment]
This has been addressed: #272 .
