### ISSUE TITLE
Things to Look Into

### ISSUE THREAD

**Issue by kwf37** [cucapra/futil#19]
# HLS Optimization
* Zhiru's papers?
* HeteroCL
* LegUp

# RTL Backends
* [Yosys](https://github.com/YosysHQ/yosys) 
* SystemVerilog
* PyMTL (Rachit)
* HardCAML (Rachit)
* CLASH (Sam)
* CoreIR (Ken)
* FIRRTL (Ken)

**Comment by sgpthomas** [comment]
Regarding HLS optimizations: [this](https://arxiv.org/abs/1805.08288) paper looks good.
