### ISSUE TITLE
Resource sharing

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#197]
Resource sharing is an optimization that let's a FuTIL program hardware components that (1) are not used at the same time, and (2) don't rely on state between uses.

### Design choices

FuTIL's control can be used to conservatively infer (1). We have a few choices for (2):
- Cells have an attribute that says if they're shareable. For example, adders and multipliers can be shared. However, a DSL compiler has no influence over this decision. Furthermore, registers generated for the FSMs cannot be shared (because all registers are shareable, or none are)
- DSL compilers name specific cells as shareable using something similar to an attribute system:
```
cells {
  a<shareable=1> = std_reg(32); 
  b = std_reg(32);
}
```
In this case, `a` is a shareable register while `b` isn't.

### Implementation

The implementation does not care about the decision above. Abstractly, it needs to:
1. For each group, compute the cells being used as inputs and outputs (this analysis is generally useful for many things so implement it separately).
2. Use the control to create a conflict graph between groups. When two groups have a conflict, they have an edge between them.
3. Traverse the graph and re-assign the shareable cells in each group. When there is a conflict, the groups get different cells.

### MVP

For the MVP, I suggest that we decide the mechanism to convey the shareability information, implement the conflict-based reassignment, and start sharing combinational elements like adders.

After merging the MVP, we can:
1. Share the FSM elements generated from compile control.
2. Figure out sharing opportunities in the Dahlia and the Systolic frontends.

**Comment by sampsyo** [comment]
This seems great! For the MVP, I think it makes the most sense to just have a "shareable" (i.e., "logically stateless") attribute on the cells? That seems like it's the easiest to implement and would at least let us try out the feasibility of the idea.
