### ISSUE TITLE
"Driver" CLI tool

### ISSUE THREAD

**Issue by sampsyo** [cucapra/futil#206]
Let's build a driver to solve all our problems!

- MVP: You give it a FuTIL program; it runs it in Verilator simulation.
- `--from` and `--to` flags for input & output formats.
- Have a mode to produce a pretty verbose log, including showing all the commands that were run.

---

Wishlist:

- [x] Simulate with Verilator (replace `gen_vcd`, etc.):
  - [x] Invoke Verilator.
  - [x] Invoke C++ compiler.
  - [x] Run the compiled simulator.
  - [x] Translate JSON to Verilator-friendly data files.
  - [x] VCD to JSON.
- [ ] Initialization.
  - [ ] Create empty JSON data files given a FuTIL program (corresponding to its memories).
  - [ ] Initialize test stuff.
- [x] Frontends.
  - [x] Invoke the Dahlia compiler.
  - [ ] Invoke arbitrary other frontends, including the systolic array thing.
- [ ] Invoke Vivado to do synthesis.
- [ ] Run Vivado HLS on a C++ or Dahlia program. (Not really directly FuTIL related.)
- [ ] Choose FuTIL passes.
- [ ] Differential testing.

**Comment by rachitnigam** [comment]
Closed by #211
