### ISSUE TITLE
Question about the README dialogue.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/futil#209]
From the README, 
```
Primitives Library: FuTIL can use customizable libraries based on the backend. The libraries live under primitives. You probably want to use primitives/std/lib with the -l flag.

`cargo run -- examples/simple.futil -l primitives/std.lib`
```

So I did exactly that:
```
% cargo run -- examples/simple.futil -l primitives/std.lib
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/futil examples/simple.futil -l primitives/std.lib`
Error: InvalidFile: Failed to read primitives/std.lib/primitives/std.lib: Not a directory (os error 20)
```

So it looks like primitives/std.lib is defaulted here given ```Failed to read primitives/std.lib/primitives/std.lib```. Removing ```primitives/std.lib``` works fine. Let me know if I'm missing something here.

**Comment by sgpthomas** [comment]
This is a typo in the readme. The `-l` flag tells the compiler the directory to find the import paths in. so `import primitives/std.lib` with `-l primitives` will tell the compiler to look for `primitives/primitives/std.lib`. The correct thing to pass to this flag is `-l .` which is the default and why it works when you don't pass the flag. You need to explicilty pass this flag when you're not in the root directory. So for example, if you're in the benchmarks directory, you'll need to pass `-l ..` to tell it to find the library relative to the parent directory.
