### ISSUE TITLE
[fud] Add working example.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/futil#215]
Adding a working example to the fud directory allows the user to walk through an example, and ensures everything installed correctly.

This could be as simple as
```examples/X.fuse```
```examples/data/X.json```

This may prove useful in the root directory's README as well, which seems to use a fake ```examples/simple.futil```

**Comment by rachitnigam** [comment]
Sounds useful! Do you want to take a crack at this?

**Comment by cgyurgyik** [comment]
Sure, no problem.

**Comment by cgyurgyik** [comment]
I'm going to look into providing some examples for each of the fud stages in a single folder, and detail it in the README so that the user can easily see how each stage works.
