### ISSUE TITLE
CI for Calyx

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#25]

**Comment by kwf37** [comment]
Circle CI ok?

**Comment by sampsyo** [comment]
Could also try [GitHub actions](https://github.com/features/actions) if you sign up for the beta…

**Comment by sgpthomas** [comment]
I'm curious about GitHub actions too, but do whatever you are comfortable with.

**Comment by kwf37** [comment]
I wanna try it out- I'm still waiting to hear back about registration for the Beta. I believe they will send me an email as soon as my account is activated for the beta.

**Comment by kwf37** [comment]
Just added a config file for Github actions that builds and tests our rust code in Calyx. We can update with new workflows (e.g. for racket code) as needed.
