### ISSUE TITLE
[fud] Add named components for Dahlia lowering to fud, FuTIL passes.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/futil#274]
Currently, with the Dahlia binary, we can do the following: 
```
./fuse foo.fuse --lower -b=futil -n=<component_name>
```
We'd like to be able to do the same in fud, so that we can use fud directly in the Relay to FuTIL lowering.

On a similar note, currently trying to run a pass on FuTIL code in fud gives an error. For example:
```
fud e --from futil program.futil --to futil -s futil.flags '-p externalize'
```
will lead to an error along the lines of: 
```ends at the same stage `futil'. This is likely an error```

This should be a simple fix as well, though maybe there's a reason this is enforced.

**Comment by rachitnigam** [comment]
1. Fixed in 5a9513dd25cbc6634641547775f0ea35fe404902
2. Fud operates on a DAG of named stages. If we allowed transformations from a step to itself, it's no longer a DAG. See main.py to see how stages like `futil-lowered` are registered. You can create a new registry with those flags.

**Comment by rachitnigam** [comment]
@cgyurgyik can you respond to this?

**Comment by cgyurgyik** [comment]
I've registered a new stage in #289 (linked) for FuTIL lowering using `-p externalize`. I didn't touch the named components in Dahlia. Right now, I just use the `fuse` binary.
