### ISSUE TITLE
[fud] stop touching my files! 

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#298]
It seems like fud touches input files when running `fud e` which updates the timestamp on the file. This confuses editors like vim that think the file has changed and throw an annoying error.

Stop Fud from doing this.

**Comment by sgpthomas** [comment]
I thought we fixed this already. did something reintroduce this? or was it never fixed

**Comment by rachitnigam** [comment]
I don't think it was ever fixed.

**Comment by sgpthomas** [comment]
ah. I have a fix stashed. never pushed it
