### ISSUE TITLE
Paper list

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#33]
This is an issue to keep track of relevant papers:

- [Competition, Micro IR](https://www2.cs.sfu.ca/~ashriram/papers/2019_MICRO_MUIR.pdf)
- [Fine-grain parallelism with minimal hardware support: a compiler-controlled threaded abstract machine](https://dl.acm.org/citation.cfm?id=106990)
- [HLS Optimization Survey](https://arxiv.org/abs/1805.08288)

Scheduling Papers:
- [Dynamically Scheduled High-level Synthesis](http://www.irisa.fr/alf/downloads/ADA/p127-josipovic.pdf)
  - [Synthesis of Synchronous Elastic Architectures](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.557.1288&rep=rep1&type=pdf)
- [Combining Dynamic & Static Scheduling in High-level Synthesis](https://jianyicheng.github.io/papers/JianyiFPGA20.pdf)

**Comment by rachitnigam** [comment]
This tracker was never really used.
