### ISSUE TITLE
`fud` execution outputs nothing to console upon error.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/futil#357]
When using `fud e <input>`, it prints nothing to console when an error occurs. However, if no error occurs, then it prints the lowered program.

**Comment by rachitnigam** [comment]
Two more things:
- `-v` also doesn't work correctly (error or otherwise)
- `-vv` fixes the problem

@sgpthomas one of your recent changes probably broke this? I couldn't figure it out quickly.
