### ISSUE TITLE
Start enforcing python formatting & linting in CI

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#364]

**Comment by rachitnigam** [comment]
The comment doesn’t say this but presumably it’s just for Fud? Or should we do this for all python scripts?

**Comment by sgpthomas** [comment]
I think we should start with fud and maybe add it to other things later. I have to figure out a standard set of tools to use first.

**Comment by sampsyo** [comment]
[flake8](https://flake8.pycqa.org/en/latest/) is the boring but effective choice! Here's one Actions setup, FWIW:
https://github.com/beetbox/mediafile/blob/d7bea5efbe00c54fbe9ca169a3ffd6c827302e7d/.github/workflows/build.yml#L58-L63

**Comment by sampsyo** [comment]
88 columns?! Kids these days and their wide screens. 😄
