### ISSUE TITLE
Utility syntax for unpacking several structs

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#4]
This is not actually that necessary, but might be an interesting challenge.
Basically I'm looking for a nice way to extract all the values from a struct at once because it can get verbose to get just the field that you need of a struct.

I'm thinking something like this:
you have a structure: (struct my-fancy-struct (field-1 field-2 field-3) #:transparent)
Suppose `a`, `b`, `c` are all `my-fancy-struct`s.
then 
```
(let-struct-unwrap my-fancy-struct (a b c)
  (body ...)
)
```
would bind the names `a-field-1`, `b-field-1`, `c-field-1`, `a-field-2`, ... in the body.

I think this might not be possible because I couldn't find a way to get the field names from a struct.

**Comment by rachitnigam** [comment]
See [match-define](https://docs.racket-lang.org/reference/match.html?q=match-define#%28form._%28%28lib._racket%2Fmatch..rkt%29._match-define%29%29):

```
(match-define (position (point x y) p2) pos)
```

Works with arbitrary nestings of structs, lists etc.
