### ISSUE TITLE
Timing, Area and Energy Backend Information

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#53]
We need to standardize how we pass information that the backend provides about the primitives up to the Futil pass framework so that we can implement binding and scheduling passes.

I think that this should probably be implemented through the library interface files. We should also consider having explicit annotations for Timing, Area, and Energy (maybe others?)

**Comment by rachitnigam** [comment]
We currently have a "fat library" style primitive definitions. The attributes implementation (from #155) can encode information like the latency and timing of a primitive. We can create specific issues for things as they come up.
