### ISSUE TITLE
ast_examples/counter.futil cannot be parsed

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/futil#57]
On running
```
./target/debug/calyx ast_examples/counter.futil
```
I get:
```
Error: 0: at line 43:
         (enable lt1 i0 const3)
         ^
expected ')', found (
```

Is the example broken? In order to make examples _always work_ with the current compiler, I recommend turning them in tests: https://github.com/cucapra/dahlia/tree/master/src/test/should-run

Also, add the example to the README (#56) if it's meant to be introductory.

**Comment by sgpthomas** [comment]
These are old examples that are no longer valid. use the ones in `examples` instead.
