### ISSUE TITLE
Improve error handling system

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#60]
- move everything over to the monadic style
- explore adding richer stack information for debugging purposes so that it is easier to figure out where errors come from. We get this from `panic!`, but `panic!` just crashes the program, making it hard to have centralized error messages
- think about keeping track of source locations in Ast so that we can point to the code in error messages. this might prove to be harder than it's worth because the Ast will be changing so much.

**Comment by rachitnigam** [comment]
We have fixed various parts of this. Let's close this issue in favor of more specific issues.
