### ISSUE TITLE
generate and install command line completion files

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#72]
The `structopt` library that we use for the command line has an option to install completion files for bash, zsh, fish, and I think other shells. It would be nice to have a way to install these files. I've already played a little bit with this using rust's `build.rs` feature. The documentation for this is here: [https://docs.rs/clap/2.33.0/clap/enum.Shell.html](https://docs.rs/clap/2.33.0/clap/enum.Shell.html)

**Comment by rachitnigam** [comment]
This has been low priority for too long now. Let's revisit this when people use FuTIL compiler often enough.
