### ISSUE TITLE
Remove Structure ast statements from the structure graph representation

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#92]
Right now we are storing a structure AST statement for each Node in the structure graph (structure.rs:19) to make it easier to convert from the rich in memory representation of the structure graph to the textual AST representation. We should be able to remove this and just store enough information in the nodes to construct the AST. This will make the StructureGraph lighterweight to use in code.

**Comment by rachitnigam** [comment]
Are we still doing this? If not, lets remove this.
